import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../../components/navbar/navbar";
import Header from "./header/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "M.Taha",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-teal-950">
      <body className={inter.className}>
        <Header />

        
        {children}
        <p className="text-gray-600">contact me on <a href="https://www.instagram.com/muhammadtaha_5575">instagram</a>
        <br />
        or contact 0335 2896488
        <br />
        or <a href="https://www.linkedin.com/in/syed-muhommad-taha-04134b2ba/">linkedin</a>
        </p>
        </body>
    </html>
  );
}
